### ISSUE TITLE
Why doesn't ikp3db exit when program exists with no exit code?

### ISSUE THREAD

**Issue by kzidane** [cmorisse/ikp3db#3] opened 2018-05-07 15:50 UTC
Been experimenting a little with `ikp3db` on Cloud9 and was just curious as to why does it make sense to keep `ikp3db` running even after the program being debugged exists [here](https://github.com/cmorisse/ikp3db/blob/3b89dde87cb90db700dd97232861e35e113e6b9d/ikp3db.py#L1867)? `ikp3db` seems to normally exist with the same exit code as the program when one is given [here](https://github.com/cmorisse/ikp3db/blob/3b89dde87cb90db700dd97232861e35e113e6b9d/ikp3db.py#L1882) and in this case there's no exit code, but is it reasonable to expect every program to explicitly exit with some status code? Does it indeed make sense to keep `ikp3db` running here instead of simply defaulting to an exit code of `0`?

Thank you!

**Comment by cmorisse** [comment] 2018-05-07 16:30
Hi,

Short answer: ikp3db should exit see here
<https://github.com/cmorisse/ikp3db/blob/3b89dde87cb90db700dd97232861e35e113e6b9d/ikp3db.py#L1913>

But it doesn't; the problem is the main program can't exit until the command_loop thread
terminates.

**Comment by kzidane** [comment] 2018-05-07 16:48
Thanks a lot for the fast reply! So is the solution simply to set `daemon` to `True` [here](https://github.com/cmorisse/ikp3db/blob/3b89dde87cb90db700dd97232861e35e113e6b9d/ikp3db.py#L1856)? Happy to PR if so.

**Comment by kzidane** [comment] 2018-05-07 16:50
PS, I tried that and it seemed to do the trick. Just not sure if there might be any side effects that I'm not foreseeing.

**Comment by cmorisse** [comment] 2018-05-07 16:58
Nice. Would you mind doing a PR please ?
I would be happy to test it.
Thanks

**Comment by kzidane** [comment] 2018-05-07 17:05
See https://github.com/cmorisse/ikp3db/pull/4. Thank you!

**Comment by kzidane** [comment] 2018-07-03 18:02
Sorry I took too long to follow up! What would be a more appropriate solution here then?

**Comment by cmorisse** [comment] 2018-08-13 09:26
Fixed in version 1.2.1 (by adding a timeout in the debugger network server loop and exiting if status is terminated.)

**Closed as completed by cmorisse** 2018-08-13 09:26 UTC

**Comment by kzidane** [comment] 2019-03-01 17:30
Just fyi this is broken in 1.4.1.
